#!/usr/bin/env bash
# Install nginx web server

sudo apt-get update
sudo apt install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo /etc/init.d/nginx start
