#!/usr/bin/env bash
# displays username, user id and home directory for each line of /etc/passwd.

input="/etc/passwd"
while IFS=: read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < $input
