#!/usr/bin/env bash
# displays username, user id and home directory for each line of /etc/passwd.

input="/etc/passwd"
while IFS= read -r username password userid groupid comment homedir cmdshell
do
    echo "$username:$userid:$homedir"
done < $input
