#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP port22, 443, 80

sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable -y
sudo ufw status numbered -y
